export const recordings = [
  {
    id: "1",
    composer: "Albéniz, Issac (1860-1909)",
    coverImage: "/covers/Albeniz-Iberia.jpg",
    composition: "Navarra completed by Déodat de Séverac",
    artists: "Alicia de Larrocha (piano)",
    conductor: "",
    ensemble: "",
    media: "Cassette",
    source: "Compact Disc",
    digital: "DDD",
    workCategory: "Piano",
    fileCategory: "Piano",
    label: "London",
    catalogNumber: "417 887-2",
    purchaseDate: "1999-07-05T00:00:00.000Z",
    value: "17.99",
    tapeNumber: "1",
    location: "Cortez, CO",
    createdAt: "2023-10-15T19:41:17.242Z",
  },
  {
    id: "2",
    composer: "Albéniz, Issac (1860-1909)",
    coverImage: "/covers/Albeniz-Iberia.jpg",
    composition: "Iberia (suite for piano, 4 books) (1906-1908)",
    artists: "Alicia de Larrocha (piano)",
    conductor: "",
    ensemble: "",
    media: "Cassette",
    source: "Compact Disc",
    digital: "DDD",
    workCategory: "Piano",
    fileCategory: "Piano",
    label: "London",
    catalogNumber: "417 887-2",
    purchaseDate: "1999-07-05T00:00:00.000Z",
    value: "17.99",
    tapeNumber: "1",
    location: "Cortez, CO",
    createdAt: "2023-10-15T19:41:17.242Z",
  },
  {
    id: "3",
    composer: "Adams, John (1947-    )",
    coverImage: "/covers/john_adams-fearful-symmetries.jpg",
    composition: "The Wound Dresser",
    artists:
      "Sanford Sylvan (baritone), Naoko Tanaka (violin), Chris Gekker (trumpet)",
    conductor: "John Adams",
    ensemble: "Orchestra of St. Lukes",
    media: "Compact Disc",
    source: "",
    digital: "DDD",
    workCategory: "Orchestral",
    fileCategory: "Orchestral",
    label: "Elektra Nonesuch",
    catalogNumber: "9 79218-2",
    purchaseDate: "1990-08-03T00:00:00.000Z",
    value: "15.99",
    tapeNumber: "",
    location: "Cortez, CO",
    createdAt: "2023-10-15T19:41:17.242Z",
  },
  {
    id: "4",
    composer: "Adams, John (1947-    )",
    coverImage: "/covers/john_adams-fearful-symmetries.jpg",
    composition: "Fearful Symmetries",
    artists: "",
    conductor: "John Adams",
    ensemble: "Orchestra of St. Lukes",
    media: "Compact Disc",
    source: "",
    digital: "DDD",
    workCategory: "Orchestral",
    fileCategory: "Orchestral",
    label: "Elektra Nonesuch",
    catalogNumber: "9 79218-2",
    purchaseDate: "1990-08-03T00:00:00.000Z",
    value: "15.99",
    tapeNumber: "",
    location: "Cortez, CO",
    createdAt: "2023-10-15T19:41:17.242Z",
  },
  {
    id: "5",
    composer: "Tchaikovsky, Peter (1840-1893)",
    coverImage: "/covers/Tchaikovsky-Donohoe.jpg",
    composition:
      "Concerto No. 2 for Piano and Orchestra in G Major, Op. 44 (original version)",
    artists:
      "Peter Donohoe (piano), Nigel Kennedy (violin), Steven Isserlis (cello)",
    conductor: "Rudolf Barshai",
    ensemble: "Bournemouth Symphony Orchestra",
    media: "CD-Recordable",
    source: "Compact Disc",
    digital: "",
    workCategory: "Piano",
    fileCategory: "Piano",
    label: "EMI",
    catalogNumber: "CDC 7 49940 2",
    purchaseDate: "1999-05-11T00:00:00.000Z",
    value: "10.99",
    tapeNumber: "RES-10001",
    location: "Cortez, CO",
    createdAt: "2023-10-15T19:41:17.242Z",
  },
  {
    id: "6",

    composer: "Tchaikovsky, Peter (1840-1893)",
    coverImage: "/covers/Tchaikovsky-Donohoe.jpg",
    composition:
      "Concerto No. 3 for Piano and Orchestra in E-flat Major, Op. 75",
    artists: "Peter Donohoe (piano)",
    conductor: "Rudolf Barshai",
    ensemble: "Bournemouth Symphony Orchestra",
    media: "CD-Recordable",
    source: "Compact Disc",
    digital: "",
    workCategory: "Piano",
    fileCategory: "Piano",
    label: "EMI",
    catalogNumber: "CDC 7 49940 2",
    purchaseDate: "1999-05-11T00:00:00.000Z",
    value: "10.99",
    tapeNumber: "RES-10001",
    location: "Cortez, CO",
    createdAt: "2023-10-15T19:41:17.242Z",
  },
  {
    id: "7",
    composer: "Orff, Carl (1895-1982)",
    coverImage: "/covers/no-image.jpg",
    composition: "Carmina Burana",
    artists:
      "Nadia Vitkoska (soprano), Kenneth Regal (tenor), William Metcalf (bass), Saratoga-Potsdam Chorus",
    conductor: "Rafael Fruhbeck de Burgos",
    ensemble: "The Philadelphia Orchestra",
    media: "Reel to Reel Tape",
    source: "Radio Broadcast",
    digital: "",
    workCategory: "Choral/Vocal",
    fileCategory: "Choral/Vocal",
    label: "",
    catalogNumber: "",
    purchaseDate: "1973-08-20T00:00:00.000Z",
    value: "",
    tapeNumber: "RR00014",
    location: "Cortez, CO",
    createdAt: "2023-10-15T19:41:17.243Z",
  },
  {
    id: "8",
    composer: "Brahms, Johannes (1833-1897)",
    coverImage: "/covers/Brahms-Katchen.jpg",
    composition: "Variations and Fugue on a Theme by Handel, Op. 24",
    artists: "Julius Katchen (piano) ",
    conductor: "",
    ensemble: "",
    media: "LP Album",
    source: "",
    digital: "",
    workCategory: "Piano",
    fileCategory: "Piano",
    label: "Ace of Diamonds Records",
    catalogNumber: "SDD 538",
    purchaseDate: "2003-05-17T00:00:00.000Z",

    value: "0.00",
    tapeNumber: "",
    location: "Cortez, CO",

    createdAt: "2023-10-15T19:41:17.243Z",
  },
  {
    id: "9",
    composer: "Brahms, Johannes (1833-1897)",
    coverImage: "/covers/Brahms-Katchen.jpg",
    composition: "Variations on a Theme of Paganini, Op. 35 (Books 1 and 2)",
    artists: "Julius Katchen (piano) ",
    conductor: "",
    ensemble: "",
    media: "LP Album",
    source: "",
    digital: "",
    workCategory: "Piano",
    fileCategory: "Piano",
    label: "Ace of Diamonds Records",
    catalogNumber: "SDD 538",
    purchaseDate: "2003-05-17T00:00:00.000Z",
    value: "0.00",
    tapeNumber: "",
    location: "Cortez, CO",
    createdAt: "2023-10-15T19:41:17.243Z",
  },
  {
    id: "10",
    composer: "Barber, Samuel (1910-1981)",
    coverImage: "/covers/barber_bso.jpg",
    composition: "My Work, Op. 323",
    artists: "George George (cello) ",
    conductor: "Walter Bruno",
    ensemble: "Orchestra of the Age of Nothing",
    media: "Compact Disc",
    digital: "DDD",
    workCategory: "Orchestral",
    fileCategory: "Cello",
    label: "Teldec",
    catalogNumber: "1234567-8",
    purchaseDate: "2023-05-18T00:00:00.000Z",
    value: "2.99",
    tapeNumber: "",
    location: "Fallston, MD",
    createdAt: "2023-10-25T15:57:32.125Z",
    source: "Radio Broadcast",
  },
];

export const performances = [
  {
    id: "1",
    performanceDate: "1988-11-18T00:00:00.000Z",
    composer: "Rachmaninoff, Sergei (1873-1943)",
    composition:
      "Rhapsody on a Theme of Paganini for Piano and Orchestra, Op. 43",
    artists: "Barry Snyder (piano)",
    conductor: "Chosei Komatsu",
    ensemble: "Baltimore Symphony Orchestra",
    concertHall: "Joseph Meyerhoff Symphony Hall",
    city: "Baltimore",
    state: "MD",
    workCategory: "Piano",
    notes:
      "Chosei Komatsu is the Affiliate Artist Conductor of the BSO. Barry Snyder is currently Associate Professor of Piano at Eastman.",
    createdAt: "2023-10-15T19:41:17.248Z",
  },
  {
    id: "2",
    performanceDate: "1988-11-18T00:00:00.000Z",

    composer: "Rachmaninoff, Sergei (1873-1943)",
    composition: "Symphony No. 2 in E Minor, Op. 27",
    artists: "",
    conductor: "Chosei Komatsu",
    ensemble: "Baltimore Symphony  Orchestra",
    concertHall: "Joseph Meyerhoff Symphony Hall",
    city: "Baltimore",
    state: "MD",
    workCategory: "Symphony",
    notes: "Chosei Komatsu is the Affiliate Artist Conductor of the BSO.",
    createdAt: "2023-10-15T19:41:17.249Z",
  },
  {
    id: "3",
    performanceDate: "1989-05-05T00:00:00.000Z",

    composer: "Schwantner, Joseph (1943-    )",
    composition: "A Sudden Rainbow",
    artists: "",
    conductor: "Christopher Seaman",
    ensemble: "Baltimore Symphony Orchestra",
    concertHall: "Joseph Meyerhoff Symphony Hall",
    city: "Baltimore",
    state: "MD",
    workCategory: "Orchestral",
    notes:
      "Christopher Seaman if the BSO's Conductor-in-Residence. This was the Baltimore premiere of this work. This was Russ's first BSO concert.....",

    createdAt: "2023-10-15T19:41:17.249Z",
  },
  {
    id: "4",
    performanceDate: "1989-05-05T00:00:00.000Z",
    composer: "Boccherini, Luigi (1743-1805)",
    composition: "Concerto for Cello and Orchestra in B-flat Major, G.482",
    artists: "Mihaly Virizlay (cello)",
    conductor: "Christopher Seaman",
    ensemble: "Baltimore Symphony Orchestra",
    concertHall: "Joseph Meyerhoff Symphony Hall",
    city: "Baltimore",
    state: "MD",
    workCategory: "Cello",
    notes: "Virizlay has been the BSOs principal cellist since 1962.",
    createdAt: "2023-10-15T19:41:17.249Z",
  },
  {
    id: "5",
    performanceDate: "1989-05-05T00:00:00.000Z",
    composer: "Brahms, Johannes (1833-1897)",
    composition: "Symphony No. 3 in F Major, Op. 90",
    artists: "",
    conductor: "Christopher Seaman",
    ensemble: "Baltimore Symphony Orchestra",
    concertHall: "Joseph Meyerhoff Symphony Hall",
    city: "Baltimore",
    state: "MD",
    workCategory: "Symphony",
    notes: "",
    __v: 0,
    createdAt: "2023-10-15T19:41:17.249Z",
  },
  {
    id: "6",
    performanceDate: "1989-05-13T00:00:00.000Z",
    composer: "Brahms, Johannes (1833-1897)",
    composition: "Variations on a Theme by Josef Haydn, Op. 56a",
    artists: "",
    conductor: "Thomas Sanderling",
    ensemble: "Baltimore Symphony Orchestra",
    concertHall: "Joseph Meyerhoff Symphony Hall",
    city: "Baltimore",
    state: "MD",
    workCategory: "Orchestral",
    notes:
      "Sanderling is currently Artistic Director of the Amsterdam Philharmonic",
    createdAt: "2023-10-15T19:41:17.249Z",
  },
  {
    id: "7",
    performanceDate: "1989-05-13T00:00:00.000Z",
    composer: "Brahms, Johannes (1833-1897)",
    composition: "Shicksalslied (Song of Destiny), Op. 54",
    artists: "BSO Chorus",
    conductor: "Thomas Sanderling",
    ensemble: "Baltimore Symphony Orchestra",
    concertHall: "Joseph Meyerhoff Symphony Hall",
    city: "Baltimore",
    state: "MD",
    workCategory: "Choral/Vocal",
    notes: "",
    createdAt: "2023-10-15T19:41:17.249Z",
  },
  {
    id: "8",
    performanceDate: "1989-05-13T00:00:00.000Z",
    composer: "Brahms, Johannes (1833-1897)",
    composition: "Mass in D Minor, Hob. XXII: 11, 'Lord Nelson Mass'",
    artists:
      "Allison Hargan, Catherine Robbin, Grayson Hirst, John Ostendorf, BSO Chorus",
    conductor: "Thomas Sanderling",
    ensemble: "Baltimore Symphony Orchestra",
    concertHall: "Joseph Meyerhoff Symphony Hall",
    city: "Baltimore",
    state: "MD",
    workCategory: "Choral/Vocal",
    notes: "",
    createdAt: "2023-10-15T19:41:17.249Z",
  },
  {
    id: "9",
    performanceDate: "1989-08-17T00:00:00.000Z",
    composer: "Weber, Carl Maria von (1786-1826)",
    composition: "Overture to 'Oberon'",
    artists: "",
    conductor: "Yuri Temirkanov",
    ensemble: "The Philadelphia Orchestra",
    concertHall: "Saratoga Performing Arts Center",
    city: "Saratoga",
    state: "NY",
    workCategory: "Orchestral",
    notes:
      "Melinda's first concert at SPAC. Our first concert conducted by Yuri Temirkanov.",
    createdAt: "2023-10-15T19:41:17.249Z",
  },
  {
    id: "10",
    performanceDate: "1989-08-17T00:00:00.000Z",
    composer: "Beethoven, Ludwig van (1770-1827)",
    composition: "Concerto No. 4 for Piano and Orchestra in G Major, Op. 58",
    artists: "Emanuel Ax (piano)",
    conductor: "Yuri Temirkanov",
    ensemble: "The Philadelphia Orchestra",
    concertHall: "Saratoga Performing Arts Center",
    city: "Saratoga",
    state: "NY",
    workCategory: "Piano",
    notes: "Great Seats! Section 2, Row D, Seats 106, 108",
    createdAt: "2023-10-15T19:41:17.249Z",
  },
  {
    id: "11",
    performanceDate: "1989-08-17T00:00:00.000Z",
    composer: "Dvořák, Antonin (1842-1904)",
    composition: "Symphony No. 8 in G Major, Op. 88",
    artists: "",
    conductor: "Yuri Temirkanov",
    ensemble: "The Philadelphia Orchestra",
    concertHall: "Saratoga Performing Arts Center",
    city: "Saratoga",
    state: "NY",
    workCategory: "Symphony",
    notes:
      "Electrifying performance! Yuri Temirkanov is the chief conductor of the Leningrad (St. Petersburg) Philharmonic as well as guest conductor of the Royal Philharmonic Orchestra.",
    createdAt: "2023-10-15T19:41:17.249Z",
  },
];
